### ISSUE TITLE
请问有网盘连接吗？

### ISSUE THREAD

**Issue by Keep-lucky** [shanyan-wcx/LiZhi#3]
github下载文件老是容易出错，请问有LiZhi的资源网盘下载链接吗？

**Comment by shanyan-wcx** [comment]
有的。https://www.aliyundrive.com/t/VKU3LX3jqSbu0R4IkCwO

**Comment by Keep-lucky** [comment]
> 有的。https://www.aliyundrive.com/t/VKU3LX3jqSbu0R4IkCwO

非常抱歉，还没来得及保存，链接失效了，请问还可以重新发一次吗？或者发邮箱609524961@qq.com，谢谢！

**Comment by shanyan-wcx** [comment]
已发邮箱
